/* src/config_clp.h.  Generated by configure.  */
/* src/config_clp.h.in.  */

/* Define to 1, 2, 3, or 4 if Aboca should be build. */
/* #undef CLP_HAS_ABC */

/* Version number of project */
#define CLP_VERSION "trunk"

/* Major Version number of project */
#define CLP_VERSION_MAJOR 9999

/* Minor Version number of project */
#define CLP_VERSION_MINOR 9999

/* Release Version number of project */
#define CLP_VERSION_RELEASE 9999
